// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/25/2026, 1:56:13 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/user/workspace/voice-ai-sandbox/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/workspace/voice-ai-sandbox/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/workspace/voice-ai-sandbox/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/workspace/voice-ai-sandbox/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/workspace/voice-ai-sandbox/plugins/**/*.{js,ts,mjs}","/home/user/workspace/voice-ai-sandbox/composables/**/*.{js,ts,mjs}","/home/user/workspace/voice-ai-sandbox/utils/**/*.{js,ts,mjs}","/home/user/workspace/voice-ai-sandbox/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/workspace/voice-ai-sandbox/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/user/workspace/voice-ai-sandbox/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/user/workspace/voice-ai-sandbox/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;